### ISSUE TITLE
Code gen broke with fragments and unions in the pre-release

### ISSUE THREAD

**Issue by hed5meg** [heftapp/graphql_codegen#239] opened 2023-02-02 00:23 UTC
**Here's my schema:**

```graphql
type HotelBooking {
  id: String!
  status: BookingStatus!
  name: String!
  amount: FiatAmount!
  rebateAmount: FiatAmount
  rewardAmount: Int!
  checkInDate: String!
  checkOutDate: String!
  itineraryId: String!
  releaseDate: String
  bookingTimestamp: String
  timestamp: String
  userEmail: String!
  lastName: String
  transactionId: String
  currencyMultiplier: Float!
  affiliateId: String
  imageThumbnail: String!
}

union Booking = HotelBooking
```
**Here's my query:**

```graphql
query FetchPastBookings($cursor : String, $sortOrder : SortOrder) {
  fetchPastBookings : pastBookings(cursor : $cursor, sortOrder: $sortOrder) {
    cursor,
    bookings
    {   ...HotelBooking }
    }
}
```

**Here's my fragment:**

```graphql
fragment HotelBooking on HotelBooking { imageThumbnail, name, checkInDate, checkOutDate, rewardAmount, lastName, itineraryId  }
```

And here is the generated code with the error bolded.

```dart
class Query$FetchPastBookings$fetchPastBookings$bookings {
  Query$FetchPastBookings$fetchPastBookings$bookings(
      {required this.$__typename});

  factory Query$FetchPastBookings$fetchPastBookings$bookings.fromJson(
      Map<String, dynamic> json) {
    switch (json["__typename"] as String) {
      case "HotelBooking":
        return Fragment$HotelBooking.fromJson(json); // ERROR

      default:
        final l$$__typename = json['__typename'];
        return Query$FetchPastBookings$fetchPastBookings$bookings(
            $__typename: (l$$__typename as String));
    }
  }
```

Am I doing something wrong in my fragment definition/query, or is this a bug? It worked fine in  graphql_codegen: ^0.11.2

Thanks!

**Comment by budde377** [comment] 2023-02-02 03:51
What is the error you are seeing?

**Comment by hed5meg** [comment] 2023-02-13 09:00
Thanks for the response. The problem is that it is trying to return a  "Fragment$HotelBooking" when the expected return type is, "Query$FetchPastBookings$fetchPastBookings$bookings".

Thanks again!

**Comment by budde377** [comment] 2023-02-13 09:10
The problem is that you're returning a non concrete type. This means that you'll need to check which concrete type is actually returned. Of course in your case you only have one, but as soon as you're updating your schema by adding a new concrete type, your app will break. So this is why we can't return the fragment directly.

**Comment by hed5meg** [comment] 2023-02-13 17:00
Thank you. This worked fine in the previous version of flutter codegen for
me. What do I need to change in my .graphql files to fix this?

**Comment by hed5meg** [comment] 2023-02-13 17:36
Heres the definition of the query:

pastBookings(cursor: String, sortOrder: SortOrder): BookingList

and here's the definition of BookingList:

union Booking = HotelBooking

type BookingList {
  bookings: [Booking!]!
  cursor: String
}

**Comment by budde377** [comment] 2023-02-15 15:51
If you write 

```graphql


type BookingList {
bookings: [HotelBooking!]!
cursor: String
}

```

it should fix it.

**Comment by budde377** [comment] 2023-02-15 16:40
And in these cases you need to assert that your are working with the right concrete type, e.g. `booking is Fragment$HotelBooling`.

**Comment by hed5meg** [comment] 2023-02-15 18:22
Yes, that's what I do today with the currently generated code. The problem is that the code generated by the latest beta doesn't actually compile which seems to be a regression. I'm prevented from updating to the new version because of this.

**Comment by hed5meg** [comment] 2023-02-15 18:23
Let's me send you a before and after example.

**Comment by hed5meg** [comment] 2023-02-15 18:30
**WORKING** GENERATED CODE **BEFORE** PACKAGE UPGRADE: graphql_codegen: ^0.11.2

```
class Query$FetchPastBookings$fetchPastBookings$bookings {
  Query$FetchPastBookings$fetchPastBookings$bookings(
      {required this.$__typename});

  factory Query$FetchPastBookings$fetchPastBookings$bookings.fromJson(
      Map<String, dynamic> json) {
    switch (json["__typename"] as String) {
      case "HotelBooking":```
        **return Query$FetchPastBookings$fetchPastBookings$bookings$$HotelBooking
            .fromJson(json); // This line compiles fine in version **
```
      default:
        final l$$__typename = json['__typename'];
        return Query$FetchPastBookings$fetchPastBookings$bookings(
            $__typename: (l$$__typename as String));
    }
  }
```

**BROKEN** GENERATED CODE **AFTER** PACKAGE UPGRADE: graphql_codegen: ^0.12.0-beta.7

```
class Query$FetchPastBookings$fetchPastBookings$bookings {
  Query$FetchPastBookings$fetchPastBookings$bookings(
      {required this.$__typename});

  factory Query$FetchPastBookings$fetchPastBookings$bookings.fromJson(
      Map<String, dynamic> json) {
    switch (json["__typename"] as String) {
      case "HotelBooking":```
        **return Fragment$HotelBooking.fromJson(json); // ERROR, this line doesn't compile **
```
      default:
        final l$$__typename = json['__typename'];
        return Query$FetchPastBookings$fetchPastBookings$bookings(
            $__typename: (l$$__typename as String));
    }
  }
}  


```

**Comment by hed5meg** [comment] 2023-02-15 18:38
You can see it clealy in the example above, the return type is wrong.

**Comment by hed5meg** [comment] 2023-02-15 18:43
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/4433533/219122977-d5c52fa7-8a76-44b7-9876-0dc7f1addd15.png">

**Comment by hed5meg** [comment] 2023-02-15 18:45
It might be worth noting the other dependent libraries that change when I upgrade to the latest version of the package as well:

<img width="596" alt="image" src="https://user-images.githubusercontent.com/4433533/219123291-34d74b46-3da0-4b15-9e9b-e0299aed6c0f.png">

**Comment by hed5meg** [comment] 2023-02-15 22:22
Sorry that I didn't do a better job with my initial explanation. Thanks for creating such an awesome codegen product and thank you for your patience!

**Comment by KhaleelSH** [comment] 2023-02-21 15:49
@budde377 any progress on this issue would be appreciated, as this is essential in any GraphQL API.

**Comment by budde377** [comment] 2023-02-21 15:54
A PR is always appreciated.

**Comment by budde377** [comment] 2023-02-21 15:58
As a work-around until I get this fixed. Try and disable context
replacement with the option: `disableContextReplacement: true`.

**Comment by KhaleelSH** [comment] 2023-02-21 18:31
@budde377 Thanks for your response. I fixed for the moment by removing `addTypename: false` from build configs.

**Comment by budde377** [comment] 2023-02-21 23:38
Should be fixed in latest pre-release.

**Closed by budde377** 2023-02-21 23:38 UTC
Labels: bug
